name: Testim E2E
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Testim Branch"
        required: true
        default: "Jia/test-webhook"
      testname:
        description: "Testim Test Name"
        required: true
        default: "Regression - Partners Hub - Desktop"
      environment:
        description: "Outsystems publish environment"
        required: true
        default: "staging"

jobs:
  run-testimio-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"
      - run: npm install -g @testim/testim-cli
      - run: npm i

      - name: Run Testim Tests
        run: |
          testim -c "config/partnershub-bo-config.js"  --token ${{ secrets.TESTIM_TOKEN }} --project ${{ secrets.TESTIM_PROJECT }} --grid "Testim-Grid" --branch ${{ github.event.inputs.branch }} --test-plan ${{ github.event.inputs.testname }}
