name: Testim E2E
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Testim Branch"
        required: true
        default: "Jia/test-webhook"
      testplan:
        description: "Testim Test Name"
        required: true
        default: "Regression - Partners Hub - Desktop"
      environment:
        description: "Outsystems publish environment"
        required: true
        default: "Staging"
      app_name:
        description: "Outsystems app name"
        required: true
        default: "PartnersHub"
      slack_url:
        description: "Slack webhook url"
        required: true

jobs:
  run-testimio-cli:
    runs-on: ubuntu-latest
    env:
      TESTIM_PROJECT: ${{ secrets.TESTIM_PROJECT }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      G_LOGIN: ${{ secrets.G_LOGIN }}
      G_PASSWORD: ${{ secrets.G_PASSWORD }}
      G_LOGIN_BO: ${{ secrets.G_LOGIN_BO }}
      G_PASSWORD_BO: ${{ secrets.G_PASSWORD_BO }}
      G_LOGIN_NON_PARTNER: ${{ secrets.G_LOGIN_NON_PARTNER }}
      G_PASSWORD_NON_PARTNER: ${{ secrets.G_PASSWORD_NON_PARTNER }}
      APP_NAME: ${{ github.event.inputs.app_name }}
      SUITE_NAME: ${{ github.event.inputs.testplan }}
      SLACK_WEBHOOK_URL: ${{ github.event.inputs.slack_url }}
      BRANCH: ${{ github.event.inputs.branch }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.0.0"
      - run: npm install -g @testim/testim-cli
      - run: npm ci

      - name: Run Testim Tests
        run: |
          testim -c "config/partnershub-bo-config.js" \
            --token "${{ secrets.TESTIM_TOKEN }}" \
            --project "${{ env.TESTIM_PROJECT }}" \
            --grid "Testim-Grid" \
            --branch "${{ github.event.inputs.branch }}" \
            --test-plan "${{ github.event.inputs.testplan }}"
