name: Testim Automation
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Testim Branch"
        required: true
        default: "main"
      testplan:
        description: "Testim Test Name"
        required: true
        default: "Regression - Partners Hub - Desktop"
      environment:
        description: "Outsystems publish environment"
        required: true
        default: "Staging"
      app_name:
        description: "Outsystems app name"
        required: true
        default: "PartnersHub"
      slack_channel_id:
        description: "Slack channel id"
        required: true

jobs:
  run-testimio-cli:
    runs-on: ubuntu-latest
    env:
      TESTIM_PROJECT: ${{ secrets.TESTIM_PROJECT }}
      TESTIM_TOKEN: ${{ secrets.TESTIM_TOKEN }}
      TESTIM_BRANCH: ${{ github.event.inputs.branch }}
      TESTIM_PLAN: ${{ github.event.inputs.testplan }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      APP_NAME: ${{ github.event.inputs.app_name }}
      SUITE_NAME: ${{ github.event.inputs.testplan }}
      SLACK_CHANNEL_ID: ${{ github.event.inputs.slack_channel_id }}
      BRANCH: ${{ github.event.inputs.branch }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "20.0.0"
      - run: npm install -g @testim/testim-cli
      - run: npm ci

      - name: Run Testim Tests
        run: |
          testim -c "config/index.js" \
            --token "$TESTIM_TOKEN" \
            --project "$TESTIM_PROJECT" \
            --grid "Testim-Grid" \
            --branch "$TESTIM_BRANCH" \
            --test-plan "$TESTIM_PLAN"
